/**
 * @file HashAuthInterceptor.island.tsx
 * @description Client-side layout engine that extracts incoming hash fragments and triggers secure server-side synchronization.
 */

// #region Imports
import { useEffect } from 'preact/hooks';
import { toast } from '@projective/ui';
// #endregion

// #region Component
export default function HashAuthInterceptor() {
	useEffect(() => {
		const hash = globalThis.location?.hash;
		if (!hash) return;

		// Clean leading hashes and map key values dynamically
		const params = new URLSearchParams(hash.substring(1));

		const error = params.get('error');
		const errorDescription = params.get('error_description');
		const accessToken = params.get('access_token');
		const refreshToken = params.get('refresh_token');

		// 1. Terminate flow if no auth triggers are inside the current fragment layout bounds
		if (!error && !accessToken) return;

		// Immediately sanitize and strip hash params from browser history to hide signatures from view leaks
		globalThis.history?.replaceState(
			null,
			document.title,
			globalThis.location.pathname + globalThis.location.search,
		);

		// 2. Gracefully process error contexts generated by invalid email expirations
		if (error) {
			const decodedError = errorDescription?.replace(/\+/g, ' ') ||
				'The validation link provided is invalid or has expired.';
			console.error(
				'[HashAuthInterceptor] Authentication error detected from link redirect:',
				decodedError,
			);

			toast.error(decodedError);

			// If verification fails, step backward toward the secure entry layout portal
			setTimeout(() => {
				globalThis.location.href = `/login?error=${encodeURIComponent(decodedError)}`;
			}, 2500);
			return;
		}

		// 3. Dispatch safe tokens toward our unified session controller interface
		if (accessToken && refreshToken) {
			console.log(
				'[HashAuthInterceptor] Capture sequence successful. Syncing credentials to server context...',
			);

			fetch('/api/v1/auth/session', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({ accessToken, refreshToken }),
			})
				.then(async (res) => {
					const data = await res.json();
					if (!res.ok) {
						throw new Error(data.message || 'Server session mapping synchronization failed.');
					}

					toast.success('Identity validated successfully! Synchronizing system access...');

					// Route based on database layout state profiles returned from our Fat service rules
					setTimeout(() => {
						if (data.value?.isOnboarded) {
							globalThis.location.href = '/dashboard';
						} else {
							globalThis.location.href = '/onboarding?step=2';
						}
					}, 1000);
				})
				.catch((err) => {
					console.error('[HashAuthInterceptor] Sync process aborted:', err);
					toast.error(err.message || 'Failed to initialize session configuration securely.');
				});
		}
	}, []);

	return null;
}
// #endregion
