-- 1. Create the 'quarantine' bucket (Private staging area)
INSERT INTO
    storage.buckets (id, name, public)
VALUES (
        'quarantine',
        'quarantine',
        false
    ) ON CONFLICT (id) DO NOTHING;

-- 2. Create the 'project' bucket (Private, RLS restricted)
INSERT INTO
    storage.buckets (id, name, public)
VALUES ('project', 'project', false) ON CONFLICT (id) DO NOTHING;

-- 3. NEW: Create 'public_assets' bucket (Publicly accessible via URL)
-- Used for Avatars, Banners, Team Logos
INSERT INTO
    storage.buckets (id, name, public)
VALUES (
        'public_assets',
        'public_assets',
        true
    ) ON CONFLICT (id) DO NOTHING;

-- 4. NEW: Create 'personal' bucket (Private, User library)
INSERT INTO
    storage.buckets (id, name, public)
VALUES ('personal', 'personal', false) ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- STORAGE RLS POLICIES
-- ============================================================

-- A. QUARANTINE POLICIES
CREATE POLICY "Authenticated users can upload to quarantine" ON storage.objects FOR
INSERT
    TO authenticated
WITH
    CHECK (bucket_id = 'quarantine');

CREATE POLICY "Users can read their own quarantine files" ON storage.objects FOR
SELECT TO authenticated USING (
        bucket_id = 'quarantine'
        AND auth.uid () = owner
    );

-- B. PROJECT POLICIES
-- (Note: 'projects.has_project_access' check is heavy for storage,
-- usually handled via Signed URLs generated by backend, but this allows direct reads if needed)
CREATE POLICY "Authenticated users can view project files" ON storage.objects FOR
SELECT TO authenticated USING (bucket_id = 'project');

-- C. PUBLIC ASSETS POLICIES
-- Allow anyone (even anon) to view public assets like avatars
CREATE POLICY "Public Assets are viewable by everyone" ON storage.objects FOR
SELECT TO public USING (bucket_id = 'public_assets');

-- D. PERSONAL LIBRARY POLICIES
-- Users can only see/manage their own files
CREATE POLICY "Users manage own personal files" ON storage.objects FOR ALL TO authenticated USING (
    bucket_id = 'personal'
    AND auth.uid () = owner
)
WITH
    CHECK (
        bucket_id = 'personal'
        AND auth.uid () = owner
    );